"""Create / remove IAM access groups, service IDs and COS bucket policies.

Principle of least privilege:
  * Readers group  -> Reader  role on ONE bucket only
  * Writers group  -> Writer  role on ONE bucket only
Nobody gets account-wide Manager access.
"""
import logging
from typing import Dict, Optional

from ibm_cloud_sdk_core import ApiException
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
from ibm_platform_services import (
    IamAccessGroupsV2,
    IamIdentityV1,
    IamPolicyManagementV1,
)
from ibm_platform_services.iam_access_groups_v2 import AddGroupMembersRequestMembersItem

from .config import Settings

log = logging.getLogger(__name__)

# Platform-defined COS service roles
ROLE_CRNS = {
    "Reader": "crn:v1:bluemix:public:iam::::serviceRole:Reader",
    "Writer": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
    "Manager": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
    "ContentReader": "crn:v1:bluemix:public:iam::::serviceRole:ContentReader",
}


def build_bucket_policy_payload(account_id: str, instance_guid: str, bucket: str) -> list:
    """Resource attributes that scope a policy to a single COS bucket."""
    return [
        {"name": "serviceName", "value": "cloud-object-storage"},
        {"name": "accountId", "value": account_id},
        {"name": "serviceInstance", "value": instance_guid},
        {"name": "resourceType", "value": "bucket"},
        {"name": "resource", "value": bucket},
    ]


class IamManager:
    def __init__(self, settings: Settings):
        self.s = settings
        auth = IAMAuthenticator(settings.admin_api_key)
        self.groups = IamAccessGroupsV2(authenticator=auth)
        self.identity = IamIdentityV1(authenticator=auth)
        self.policies = IamPolicyManagementV1(authenticator=auth)

    # ---------- Access groups ----------
    def get_or_create_group(self, name: str, description: str) -> str:
        existing = self.groups.list_access_groups(account_id=self.s.account_id).get_result()
        for g in existing.get("groups", []):
            if g["name"] == name:
                log.info("Access group exists: %s", name)
                return g["id"]
        res = self.groups.create_access_group(
            account_id=self.s.account_id, name=name, description=description
        ).get_result()
        log.info("Created access group: %s", name)
        return res["id"]

    def add_member(self, group_id: str, iam_id: str, member_type: str = "service") -> None:
        member = AddGroupMembersRequestMembersItem(iam_id=iam_id, type=member_type)
        self.groups.add_members_to_access_group(access_group_id=group_id, members=[member])

    # ---------- Service IDs ----------
    def get_or_create_service_id(self, name: str, description: str) -> Dict[str, str]:
        found = self.identity.list_service_ids(
            account_id=self.s.account_id, name=name
        ).get_result()
        for sid in found.get("serviceids", []):
            if sid["name"] == name:
                return {"id": sid["id"], "iam_id": sid["iam_id"]}
        res = self.identity.create_service_id(
            account_id=self.s.account_id, name=name, description=description
        ).get_result()
        return {"id": res["id"], "iam_id": res["iam_id"]}

    def create_api_key(self, name: str, iam_id: str) -> str:
        res = self.identity.create_api_key(
            name=name, iam_id=iam_id, account_id=self.s.account_id,
            description="Generated by ibm-cos-iam-access-control",
        ).get_result()
        return res["apikey"]  # only returned once!

    # ---------- Policies ----------
    def attach_bucket_policy(self, group_id: str, role: str) -> str:
        """Grant `role` on the configured bucket to an access group."""
        attrs = build_bucket_policy_payload(
            self.s.account_id, self.s.instance_guid, self.s.bucket
        )
        res = self.policies.create_policy(
            type="access",
            subjects=[{"attributes": [{"name": "access_group_id", "value": group_id}]}],
            roles=[{"role_id": ROLE_CRNS[role]}],
            resources=[{"attributes": attrs}],
            description=f"{role} on bucket {self.s.bucket} (managed by cos-iam)",
        ).get_result()
        log.info("Attached %s policy on bucket '%s' to group %s", role, self.s.bucket, group_id)
        return res["id"]

    # ---------- Orchestration ----------
    def setup(self) -> Dict[str, str]:
        """Provision groups, service IDs, memberships, policies and API keys."""
        readers = self.get_or_create_group(self.s.readers_group, "Read-only access to COS bucket")
        writers = self.get_or_create_group(self.s.writers_group, "Read/write access to COS bucket")

        r_sid = self.get_or_create_service_id(self.s.reader_service_id, "Demo reader identity")
        w_sid = self.get_or_create_service_id(self.s.writer_service_id, "Demo writer identity")

        self.add_member(readers, r_sid["iam_id"])
        self.add_member(writers, w_sid["iam_id"])

        self.attach_bucket_policy(readers, "Reader")
        self.attach_bucket_policy(writers, "Writer")

        return {
            "reader_api_key": self.create_api_key(f"{self.s.prefix}-reader-key", r_sid["iam_id"]),
            "writer_api_key": self.create_api_key(f"{self.s.prefix}-writer-key", w_sid["iam_id"]),
        }

    def cleanup(self) -> None:
        """Best-effort removal of everything created by setup()."""
        for name in (self.s.readers_group, self.s.writers_group):
            groups = self.groups.list_access_groups(account_id=self.s.account_id).get_result()
            for g in groups.get("groups", []):
                if g["name"] == name:
                    self.groups.delete_access_group(access_group_id=g["id"], force=True)
                    log.info("Deleted access group %s", name)
        for name in (self.s.reader_service_id, self.s.writer_service_id):
            found = self.identity.list_service_ids(account_id=self.s.account_id, name=name).get_result()
            for sid in found.get("serviceids", []):
                if sid["name"] == name:
                    self.identity.delete_service_id(id=sid["id"])
                    log.info("Deleted service ID %s", name)
